### ISSUE TITLE
installing simple_parsing with pip in python3.8 installs dataclasses-0.6

### ISSUE THREAD

**Issue by lebrice** [lebrice/SimpleParsing#18]

**Comment by Wooza** [comment]
This causes an interesting behavior where every new release of `simple-parsing` adds or removes the `dataclasses` dependency, when we update the dependencies of our project.

I'm not an expert on dependency management in Python, but the official [documentation](https://www.python.org/dev/peps/pep-0508/#environment-markers) proposes something like `dataclasses;python_version<"3.7"` to specify dependencies which depend on the current python version.

Maybe using this instead of optionally adding `dataclasses` to the dependency list can solve this problem?

**Comment by lebrice** [comment]
Thanks @Wooza , Indeed that's annoying, I'll look into using that, and If all goes well, I should have a fix pushed in the next few days. I'll post something here when that's the case.

In the meantime, you can sidestep this issue by installing simple-parsing with the `--ignore-deps` flag, but you'd need to manually install `dataclasses` if you want to use it with python=3.6.

Thanks for using this package, by the way! Do you mind if I ask what kind of project you're working on?

**Comment by lebrice** [comment]
Ok, this should be fixed, as of v0.0.11.post12, let me know if you still encounter this issue!

**Comment by Wooza** [comment]
@lebrice thank you for fixing this.

We are working on a tool for automated test generation in Python, similar to what already exists for Java, e.g., [EvoSuite](https://www.evosuite.org/) or [Randoop](https://randoop.github.io/randoop/). We will make our first public release within the next weeks.

**Comment by Wooza** [comment]
@lebrice 
If you are still interested, we just put out our first release: [Pynguin](https://github.com/se2p/pynguin).
