### ISSUE TITLE
Make `Serializable` into a wrapping class

### ISSUE THREAD

**Issue by aronla** [lebrice/SimpleParsing#35]
Instead of having to inherit from Serializable, it would be great to just be able to use it as static methods on the dataclasses. The problem now is that it pollutes the namespace of the dataclass so instead of seeing just the fields you are interested in you also see things such as `save` etc.

Thanks for a much needed and easy to use library!

**Comment by lebrice** [comment]
Hello there, thanks!
Interesting suggestion. I'm not sure I totally understand what it should look like after such a change though, would you mind giving me an example use case?

Also, there are some cool features of the Serializable class that depend on having access to all its defined subclasses, so that you could, for instance, given these classes:
```python
@dataclass
class Animal(Serializable):
   name: str

@dataclass
class Cat(Animal)
   fur_color: str = "brown"

billy = Car("Billy", fur_color="orange")
billy.save("billy.json")
```
Do something like:
```
billy_reloaded = Animal.load("billy.json", drop_extra_fields=False)
assert billy == billy_reloaded
assert isinstance(billy_reloaded, Cat)
```

The important thing here is that Serializable can dynamically determine the best class to use for deserialization when there are extra keys, and in order to do that, it needs to have a list of all the potential classes to use (which it currently constructs as you create new subclasses of Serializable.

This, by the way, is also the reason I don't think that simply using the methods on Serializable as static methods (e.g. `Serializable.save(my_object, "my_object.yaml")` would work, although I will test this out once you help me get a better idea of what the use-case would look like. 

I hope this is somewhat clear, let me know what you think.

**Comment by lebrice** [comment]
I'm gonna close this for now. Please don't hesitate to reopen this if you feel my answer hasn't addressed your concern!
