### ISSUE TITLE
Nested parameter name with dataclass

### ISSUE THREAD

**Issue by jhagege** [lebrice/SimpleParsing#46]
Hi, great library, thanks ! 
I have an issue with nested parser from dataclass. 

When trying to create a parser from a dataclass
```

@dataclass
class JBuildRelease:
    id: int 
    url: str  
    docker_image: str  

    parser = simple_parsing.ArgumentParser()
    parser.add_argument('--run_id', type=str)
    parser.add_arguments(JBuildRelease, dest='jbuild', prefix='jbuild')
    args = parser.parse_args()
```

I get the following:

> usage: release.py [-h] [--run_id str] --id int --url str --docker_image str
> release.py: error: the following arguments are required: --id, --url, --docker_image
> 

I wish the arguments would be prefixed like so: --jbuild.id 1 --jbuild.url url --jbuild.docker_image image
Is this flow supported ?

**Comment by lebrice** [comment]
Hello @jhagege , thanks for posting!

This is interesting. You've actually uncovered two bugs here!

The first was easy to fix, which is that the `prefix` argument wasn't really being used as expected. I've added a test file [here](https://github.com/lebrice/SimpleParsing/blob/lebrice/issue46/test/test_issue_46.py) to reproduce your issue.

With that small bug out of the way, it's important to point out that the prefix won't necessarily get an added ".", so you'd actually need to set `prefix="jbuild."`, otherwise you'd get arguments like `--jbuildid some_id --jbuildurl some_url`.

The second is something I haven't thought about in a while, and is a bit trickier to tackle, which is that there is no conflict detection between the "regular" args and the "field" args. (See #49 ).

I'll probably be update the PyPI version once #50 passes all tests. 

Thanks again for posting!

**Comment by jhagege** [comment]
Thanks for your quick handling :)
